/**
 * Layer 2 - Strategy Engine
 * Constants
 *
 * Shared constants for weakness codes, supporting factors, and other enumerations.
 */

// ==================== Weakness Codes ====================

/**
 * Weakness codes from Layer 1 evaluation
 * These should match the codes generated by Layer 1
 */
export const WeaknessCodes = {
  /** Bullets use weak action verbs */
  WEAK_VERBS: 'weak_verbs',
  /** Bullets lack quantifiable metrics */
  NO_METRICS: 'no_metrics',
  /** Descriptions are too generic */
  GENERIC_DESCRIPTIONS: 'generic_descriptions',
  /** Skills section is sparse */
  FEW_SKILLS_LISTED: 'few_skills_listed',
  /** Contact information is incomplete */
  MISSING_CONTACT_INFO: 'missing_contact_info',
  /** Education details are incomplete */
  INCOMPLETE_EDUCATION: 'incomplete_education',
  /** Work history has gaps */
  EMPLOYMENT_GAPS: 'employment_gaps',
  /** Resume is too long */
  TOO_LONG: 'too_long',
  /** Resume is too short */
  TOO_SHORT: 'too_short',
  /** Formatting issues detected */
  POOR_FORMATTING: 'poor_formatting',
} as const;

export type WeaknessCode = (typeof WeaknessCodes)[keyof typeof WeaknessCodes];

// ==================== Supporting Factor Codes ====================

/**
 * Supporting factor codes for mode selection reasoning
 */
export const SupportingFactorCodes = {
  /** Critical skills are missing for the target role */
  CRITICAL_MISSING_SKILLS: 'critical_missing_skills_critical',
  /** Target seniority doesn't match resume seniority */
  SENIORITY_MISMATCH: 'seniority_mismatch_critical',
  /** Target industry doesn't match resume industry */
  INDUSTRY_MISMATCH: 'industry_mismatch',
  /** Bullet points have weak action verbs or lack metrics */
  WEAK_BULLETS_HIGH: 'weak_bullets_high',
  /** Experience descriptions are too vague */
  VAGUE_EXPERIENCE_FLAG: 'vague_experience_flag',
} as const;

export type SupportingFactorCode = (typeof SupportingFactorCodes)[keyof typeof SupportingFactorCodes];

// ==================== Primary Reason Codes ====================

/**
 * Primary reason codes for mode selection
 */
export const PrimaryReasonCodes = {
  /** Resume score is below minimum threshold */
  RESUME_BELOW_THRESHOLD: 'resume_below_threshold',
  /** Interview rate is low after sufficient volume */
  LOW_INTERVIEW_RATE_AFTER_VOLUME: 'low_interview_rate_after_volume',
  /** Default healthy state (no issues detected) */
  HEALTHY_STATE_DEFAULT: 'healthy_state_default',
  /** No applications yet */
  NO_APPLICATIONS: 'no_applications',
} as const;

export type PrimaryReasonCode = (typeof PrimaryReasonCodes)[keyof typeof PrimaryReasonCodes];

// ==================== Confidence Levels ====================

/**
 * Confidence level values used across the system
 */
export const ConfidenceLevels = {
  LOW: 'low',
  MEDIUM: 'medium',
  HIGH: 'high',
} as const;

export type ConfidenceLevel = (typeof ConfidenceLevels)[keyof typeof ConfidenceLevels];

// ==================== Thresholds for Confidence Calculation ====================

/**
 * Thresholds for determining confidence levels
 */
export const ConfidenceThresholds = {
  /** Minimum resume score for high confidence */
  HIGH_RESUME_SCORE_MIN: 70,
  /** Maximum resume score for low confidence */
  LOW_RESUME_SCORE_MAX: 50,
  /** Minimum applications for data confidence */
  MIN_APPLICATIONS_FOR_CONFIDENCE: 10,
} as const;

// ==================== Preserve Patterns for Canonicalization ====================

/**
 * Regular expression patterns for terms that should preserve special characters
 * during canonicalization (e.g., programming languages with special chars)
 */
export const PreservePatterns = [
  /** C# programming language */
  /^c#$/i,
  /** C++ programming language */
  /^c\+\+$/i,
  /** F# programming language */
  /^f#$/i,
  /** .NET framework */
  /^\.net$/i,
  /** Node.js runtime */
  /^node\.js$/i,
  /** Vue.js framework */
  /^vue\.js$/i,
  /** Angular.js framework */
  /^angular\.js$/i,
  /** D3.js library */
  /^d3\.js$/i,
  /** Three.js library */
  /^three\.js$/i,
  /** Express.js framework */
  /^express\.js$/i,
  /** Next.js framework */
  /^next\.js$/i,
  /** Nest.js framework */
  /^nest\.js$/i,
] as const;

/**
 * Check if a term should preserve special characters during canonicalization
 */
export function shouldPreserveSpecialChars(term: string): boolean {
  return PreservePatterns.some((pattern) => pattern.test(term));
}

// ==================== Mode Transition Rules ====================

/**
 * Valid mode transition combinations for hysteresis checking
 */
export const ModeTransitions = {
  /** Transitions between APPLY_MODE and RETHINK_TARGETS */
  APPLY_RETHINK: ['APPLY_MODE', 'RETHINK_TARGETS'] as const,
  /** Transitions involving IMPROVE_RESUME_FIRST */
  IMPROVE_TRANSITIONS: ['IMPROVE_RESUME_FIRST'] as const,
} as const;

/**
 * Check if a transition is between APPLY_MODE and RETHINK_TARGETS
 */
export function isApplyRethinkTransition(
  currentMode: string,
  proposedMode: string
): boolean {
  const applyRethinkModes = new Set(ModeTransitions.APPLY_RETHINK);
  return applyRethinkModes.has(currentMode) && applyRethinkModes.has(proposedMode);
}
