'use client';

import { useState } from 'react';
import { HelpCircle, X, Loader2 } from 'lucide-react';

interface ExplanationButtonProps {
  explanationType: 'strategy' | 'action' | 'job_ranking' | 'score' | 'gap' | 'plan' | 'progress';
  contextId?: string;
  userId: string;
  context?: Record<string, unknown>;
  tone?: 'professional' | 'empathetic' | 'encouraging' | 'direct';
  className?: string;
  label?: string;
}

export function ExplanationButton({ 
  explanationType, 
  contextId, 
  userId, 
  context,
  tone = 'professional',
  className = '',
  label = 'Why?'
}: ExplanationButtonProps) {
  const [isOpen, setIsOpen] = useState(false);
  const [loading, setLoading] = useState(false);
  const [explanation, setExplanation] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);

  const fetchExplanation = async () => {
    setLoading(true);
    setError(null);
    
    try {
      const res = await fetch('/api/coach/explain', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          explanation_type: explanationType,
          context_id: contextId,
          user_id: userId,
          tone,
          ...context,
        }),
      });
      
      if (!res.ok) {
        throw new Error('Failed to get explanation');
      }
      
      const data = await res.json();
      if (data.success && data.explanation) {
        setExplanation(data.explanation);
      } else {
        throw new Error(data.error || 'Failed to get explanation');
      }
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to get explanation');
    } finally {
      setLoading(false);
    }
  };

  const handleClick = async () => {
    if (!explanation) {
      await fetchExplanation();
    }
    setIsOpen(true);
  };

  return (
    <>
      <button
        onClick={handleClick}
        className={`inline-flex items-center gap-1 text-sm text-blue-600 hover:text-blue-700 transition-colors ${className}`}
        disabled={loading}
      >
        {loading ? (
          <Loader2 className="w-4 h-4 animate-spin" />
        ) : (
          <HelpCircle className="w-4 h-4" />
        )}
        <span>{label}</span>
      </button>

      {/* Popover */}
      {isOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/30">
          <div 
            className="absolute inset-0"
            onClick={() => setIsOpen(false)}
          />
          <div className="relative bg-white rounded-xl shadow-2xl max-w-lg w-full max-h-[80vh] overflow-hidden">
            {/* Header */}
            <div className="flex items-center justify-between p-4 border-b border-gray-100">
              <h3 className="font-semibold text-gray-800">AI Coach Explanation</h3>
              <button
                onClick={() => setIsOpen(false)}
                className="p-1 hover:bg-gray-100 rounded-full transition-colors"
              >
                <X className="w-5 h-5 text-gray-500" />
              </button>
            </div>

            {/* Content */}
            <div className="p-4 overflow-y-auto max-h-[60vh]">
              {loading && (
                <div className="flex items-center justify-center py-8">
                  <Loader2 className="w-8 h-8 animate-spin text-blue-500" />
                </div>
              )}

              {error && (
                <div className="bg-red-50 text-red-700 p-4 rounded-lg">
                  {error}
                </div>
              )}

              {explanation && !loading && (
                <div className="prose prose-sm max-w-none">
                  <div className="whitespace-pre-wrap text-gray-700">
                    {explanation}
                  </div>
                </div>
              )}
            </div>

            {/* Footer */}
            <div className="p-4 border-t border-gray-100 bg-gray-50">
              <p className="text-xs text-gray-500">
                This explanation is generated by your AI Career Coach based on your profile and activity.
              </p>
            </div>
          </div>
        </div>
      )}
    </>
  );
}
